### ISSUE TITLE
How do I change the indicator?

### ISSUE THREAD

**Issue by vimcat** [nozzle/nzScrollbar#7]
![screen shot 2015-03-10 at 1 27 11 pm](https://cloud.githubusercontent.com/assets/76280/6584543/5304b4c2-c729-11e4-9c33-28a8442ee586.png)

I was able nzScrollbar-indicator-wrap to look like the attached image but the indicator is not taking the color change and if I force the display to show all the time, it turns the whole wrap black.

**Comment by tannerlinsley** [comment]
Let's take a peak at your css?

**Comment by vimcat** [comment]
.scrollContainer {
          overflow: auto;
          margin: auto auto;
          &.nzScrollbar {
            border: 1px solid #E9E9E7;
            .nzScrollbar-indicator-wrap {
              background-color: #ddd;
              opacity: 1;
              width: 10px;
              &.noScroll {
                display: none;
              }
              .nzScrollbar-indicator {
                background-color: blue !important;
                display: block !important;
                height: 20px;
                width: 10px;
              }
            }
          }
          &.noScroll {
            border: 0 none;
          }
        }

**Comment by tannerlinsley** [comment]
This works to override the colors:

```css
 /* This alters the opacity when you hover over the scrollbox */
.nzScrollbar:hover .nzScrollbar-indicator-wrap {
    opacity: 1;
}
/* This is the background color of the bar */
.nzScrollbar .nzScrollbar-indicator-wrap:hover {
    background-color: rgba(0, 0, 0, 0.2);
}
/* this is the background color of the indicator */
.nzScrollbar {
    .nzScrollbar-indicator-wrap {
        .nzScrollbar-indicator {
            background-color: red !important;
        }
    }
}
```

Here is a link to the plunkr demo with that css inserted at the bottom:  http://codepen.io/anon/pen/NPOGpd
